#write a function nearly_equal to test two strings are nearly equal.
#Two strings a and b are nearly equal when a can be generated by a single mutation on b.
def nearly_equal(a, b):
    if len(a) != len(b):
        return False
    count = 0
    for i in range(len(a)):
        if a[i] != b[i]:
            count += 1
            if count > 1:
                return False
    return count == 1
print(nearly_equal("book", "book"))  
print(nearly_equal("test", "test"))  
print(nearly_equal("apple", "apple"))
print(nearly_equal("cat", "cuts"))
print(nearly_equal("hello", "hallo"))